### ISSUE TITLE
All to be continued screens

### ISSUE THREAD

**Issue by TheTinWhisker** [DerekPascarella/BirdcageOfHorrors-EnglishPatchDreamcast#10]
The to be continued screen says "there're ### days left.  In written English, it is more appropriate to use the full phrase "there are" instead of the contraction "there're".

Also, using there're just doesn't look right.

**Comment by DerekPascarella** [comment]
This is the original "To be continued..." image and is not something I created for the translation patch. It's a perfectly acceptable contraction (as you've pointed out), albeit a slightly awkward one to see in written text (rather than spoken).

That said, the effort to actually change this screen across the entire series would not even be close to worth it.

Thanks for for your interest in the project, and I hope you're enjoying it!

**Comment by TheTinWhisker** [comment]
I am enjoying it.  I wish more Japanese releases were translated.
