### ISSUE TITLE
Translator's Note Positioning

### ISSUE THREAD

**Issue by mSchul4** [DerekPascarella/BirdcageOfHorrors-EnglishPatchDreamcast#9]
Some lines early on in Chapter 1 (and onward, probably?) have translator's notes for Japanese/German terminology and phrases tacked on to the ends of their first appearance. Moving the notes up to the top of the screen as separate lines, like the questions during the interview segments, would make the subs easier to read.

Some examples: 
Chapter 1-002 (Track 03): 
I'm not at liberty to say much more. Well, let us refer to them as "The Komadori". [komadori = Japanese robin]
-->
TOP: _komadori = Japanese robin_
BOTTOM: I'm not at liberty to say much more. Well, let us refer to them as "The Komadori".

Chapter 1-003 (Track 04): 
The name of the apartment building is "Grauenheim". [German: "grauen = horror, shiver; Heim = home] 
--> 
TOP: _German: "grauen = horror, shiver; "heim" = home_ 
BOTTOM: The name of the apartment building is "Grauenheim".

**Comment by DerekPascarella** [comment]
I appreciate the suggestion. However, due to the automated way I am subbing 407 FMVs, I have limitations with these things. The interview videos were manually subbed. I could make exceptions for some videos and do them manually too, but I have to draw a line somewhere, otherwise I'll keep going and never stop! Haha.

Again, thank you. Closed for now.
